In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
data = pd.read_excel('aguasfeo.xlsx')
data.describe

<bound method NDFrame.describe of          Sabor  Tamano Hielo  Calificacion
0      Naranja   chica    si           9.5
1      Naranja   chica    no           7.0
2      Naranja  grande    si          10.0
3      Naranja  grande    no           7.5
4         Coco   chica    si           7.5
5         Coco   chica    no           6.0
6         Coco  grande    si           8.0
7         Coco  grande    no           7.0
8       Kahlua   chica    si           9.0
9       Kahlua   chica    no           7.0
10      Kahlua  grande    si           9.5
11      Kahlua  grande    no           7.5
12  Fresa-pina   chica    si           8.5
13  Fresa-pina   chica    no           7.0
14  Fresa-pina  grande    si           9.0
15  Fresa-pina  grande    no           6.0
16     Sandia    chica    si           7.0
17     Sandia    chica    no           5.0
18     Sandia   grande    si           7.5
19     Sandia   grande    no           6.0>

In [65]:
#remplazando los valores de las variables cualitativas por valores numericos
tamano = data['Tamano'].replace('chica', 0).replace('grande', 1)
hielo = data['Hielo'].replace('no', 0).replace('si', 1)

In [66]:
data[data['Sabor']=='Naranja']

,Sabor,Tamano,Hielo,Calificacion
0,Naranja,chica,si,9.5
1,Naranja,chica,no,7.0
2,Naranja,grande,si,10.0
3,Naranja,grande,no,7.5


In [67]:
data['Naranja'] = np.where(data['Sabor'] == 'Naranja', 1, 0)
data['Coco'] = np.where(data['Sabor'] == 'Coco', 1, 0)
data['Kahlua'] = np.where(data['Sabor'] == 'Kahlua', 1, 0)
data['Fresa_pina'] = np.where(data['Sabor'] == 'Fresa-pina', 1, 0)
data['Sandia'] = np.where(data['Sabor'] == 'Sandia', 1, 0)

In [68]:
data.head()

,Sabor,Tamano,Hielo,Calificacion,Naranja,Coco,Kahlua,Fresa_pina,Sandia
0,Naranja,chica,si,9.5,1,0,0,0,0
1,Naranja,chica,no,7.0,1,0,0,0,0
2,Naranja,grande,si,10.0,1,0,0,0,0
3,Naranja,grande,no,7.5,1,0,0,0,0
4,Coco,chica,si,7.5,0,1,0,0,0


In [69]:
from sklearn.linear_model import LinearRegression

X = np.column_stack((
    tamano,
    hielo,
    data['Naranja'],
    data['Coco'],
    data['Kahlua'],
    data['Fresa_pina'],
    data['Sandia']
))
y = data['Calificacion']

lr = LinearRegression()
lr.fit(X, y)

pred = lr.predict(X)

In [80]:
import statsmodels.api as sm

# Agregar constante para el intercepto
X_OLS = sm.add_constant(X)

# Modelo OLS
modelo_OLS = sm.OLS(y, X_OLS)

# Ajustar modelo
resultado_OLS = modelo_OLS.fit()

# Ver resultados completos
print(resultado_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:           Calificacion   R-squared:                       0.933
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     30.17
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           6.63e-07
Time:                        17:45:50   Log-Likelihood:                -6.6960
No. Observations:                  20   AIC:                             27.39
Df Residuals:                      13   BIC:                             34.36
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3125      0.135     39.240      0.0

In [81]:
print('Coeficientes:')
print(resultado_OLS.params)

print('Errores estandar:')
print(resultado_OLS.bse)

print('Estadisticos t:')
print(resultado_OLS.tvalues)

print('P-values:')
print(resultado_OLS.pvalues)

Coeficientes:
const    5.3125
x1       0.4500
x2       1.9500
x3       0.6125
x4       1.1125
x5       1.7375
x6       1.9875
x7      -0.1375
dtype: float64
Errores estandar:
const    0.135386
x1       0.187596
x2       0.187596
x3       0.189540
x4       0.189540
x5       0.189540
x6       0.189540
x7       0.189540
dtype: float64
Estadisticos t:
const    39.239701
x1        2.398770
x2       10.394671
x3        3.231505
x4        5.869468
x5        9.166922
x6       10.485903
x7       -0.725440
dtype: float64
P-values:
const    6.865475e-15
x1       3.215896e-02
x2       1.146171e-07
x3       6.557577e-03
x4       5.505785e-05
x5       4.888182e-07
x6       1.034724e-07
x7       4.810381e-01
dtype: float64


In [70]:
print('Intercepto:', lr.intercept_)
print('Coeficientes:', lr.coef_)
print('R2:', lr.score(X, y))

Intercepto: 5.175000000000001
Coeficientes: [0.45  1.95  2.125 0.75  1.875 1.25  0.   ]
R2: 0.9329915781764921


In [71]:
# Errores
error = y - pred

# RSS
RSS = np.sum(error**2)

# Numero de datos
n = len(y)

# Numero de parametros
p = X.shape[1] + 1

# Varianza del error
sigma2 = RSS / (n-p)

print('RSS:', RSS)
print('Varianza del error:', sigma2)

RSS: 2.2874999999999988
Varianza del error: 0.1906249999999999


In [72]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [73]:
OrdinalEncoder?
OneHotEncoder?

Init signature:
OneHotEncoder(
    *,
    categories='auto',
    drop=None,
    sparse_output=True,
    dtype=<class 'numpy.float64'>,
    handle_unknown='error',
    min_frequency=None,
    max_categories=None,
    feature_name_combiner='concat',
)
Docstring:     
Encode categorical features as a one-hot numeric array.

The input to this transformer should be an array-like of integers or
strings, denoting the values taken on by categorical (discrete) features.
The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
encoding scheme. This creates a binary column for each category and
returns a sparse matrix or dense array (depending on the ``sparse_output``
parameter).

By default, the encoder derives the categories based on the unique values
in each feature. Alternatively, you can also specify the `categories`
manually.

This encoding is needed for feeding categorical data to many scikit-learn
estimators, notably linear models and SVMs with the standard kernels.

Note: a o

In [74]:
# Tamano
encoder_tamano = OrdinalEncoder(categories=[['chica','grande']])
tamano = encoder_tamano.fit_transform(data[['Tamano']])

# Hielo
encoder_hielo = OrdinalEncoder(categories=[['no','si']])
hielo = encoder_hielo.fit_transform(data[['Hielo']])

# Sabor
encoder_sabor = OneHotEncoder(sparse_output=False)
sabores = encoder_sabor.fit_transform(data[['Sabor']])

In [75]:
X = np.column_stack((tamano, hielo, sabores))

y = data['Calificacion']
print(X)
print(y)

[[0. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]]
0      9.5
1      7.0
2     10.0
3      7.5
4      7.5
5      6.0
6      8.0
7      7.0
8      9.0
9      7.0
10     9.5
11     7.5
12     8.5
13     7.0
14     9.0
15     6.0
16     7.0
17     5.0
18     7.5
19     6.0
Name: Calificacion, dtype: float64


In [76]:
lr = LinearRegression()
lr.fit(X,y)

print('Intercepto:', lr.intercept_)
print('Coeficientes:', lr.coef_)
print('R2:', lr.score(X,y))

Intercepto: 6.375
Coeficientes: [ 0.45   1.95  -0.45   0.05   0.675  0.925 -1.2  ]
R2: 0.9329915781764921


In [83]:
import statsmodels.api as sm
# Agregar columna de unos para beta 0
X = sm.add_constant(X)


# REGRESION OLS
modelo = sm.OLS(y, X)

resultado = modelo.fit()


# Resultados
print(resultado.summary())

                            OLS Regression Results                            
Dep. Variable:           Calificacion   R-squared:                       0.933
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     30.17
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           6.63e-07
Time:                        17:48:24   Log-Likelihood:                -6.6960
No. Observations:                  20   AIC:                             27.39
Df Residuals:                      13   BIC:                             34.36
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.3125      0.135     39.240      0.0

In [87]:
print(resultado.params)

const    5.3125
x1       0.4500
x2       1.9500
x3       0.6125
x4       1.1125
x5       1.7375
x6       1.9875
x7      -0.1375
dtype: float64
